# -*- coding: utf-8 -*-
"""
/***************************************************************************
 guitests
                                 A QGIS plugin
 d
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-21
        copyright            : (C) 2021 by Jan Caha
        email                : as@asda.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load guitests class from file guitests.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .erosion_data_preparation_plugin import ErosionDataPreparationPlugin
    return ErosionDataPreparationPlugin(iface)
