name: SQL to SQLite

on:
  push:
     paths:
      - .github/workflows/**
      - db_catalog/**

jobs:

  test:
  
    name: test package
    
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2
      
      - uses: s-weigand/setup-conda@v1.0.5
        with:
          update-conda: true
          python-version: 3.8
          conda-channels: anaconda, conda-forge

      - name: Install python dependency packages
        run: |
          conda install pip numpy gdal
          
      - name: SQL setup
        run: |
          sudo systemctl start mysql.service
          mysql -u root -proot < ./db_catalog/e3dcatalog_20210629.sql
          mysql -u root -proot –e “show databases;”
          mysql -u root -proot -e 'SHOW TABLES FROM testcatalog;'
          
      - name: Convert MySQL to SQLite
        run: |
          python mysql_to_sqlite.py
      
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'db_catalog'
          author_name: github-actions
          author_email: github-actions@github.com
          message: "current catalog update"