name: SQL to SQLite

on:
  push:
     paths:
      - .github/workflows/**
      - db_catalog/**

jobs:

  test:
  
    name: test package
    
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Install Linux libraries
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install --yes libudunits2-dev libgdal-dev libgeos-dev libproj-dev gdal-bin libspatialindex-dev
          
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      
      - name: Install Python packages
        run: |
          pip install wheel
          pip install GDAL==`gdal-config --version`
      
      - name: SQL setup
        run: |
          sudo systemctl start mysql.service
          mysql -u root -proot < ./db_catalog/e3dcatalog_20210629.sql
          
      - name: Convert MySQL to SQLite
        run: |
          python ./db_catalog/mysql_to_sqlite.py
      
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'db_catalog'
          author_name: github-actions
          author_email: github-actions@github.com
          message: "current catalog update"